name: CI

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Use the appropriate version for norminette

      - name: Install norminette
        run: python3 -m pip install norminette

      - name: Run norminette
        run: find . | grep cub3d | head -1 ; norminette parsing incs libft common cub3D.c error c3d_math
