name: CI
#
on:
  push
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run norminette
        run: norminette $(find . -type d | grep cubed | head -1)
